_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.96122694015503
  - 40.71493574852984
  - 17
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: nag-bk-toxicity-map
source: "mapbox:///mapbox.mapbox-streets-v5,nag-brooklyn.702fdc44"
styles: 
  - style.mss
  - roads.mss
  - data-layers.mss
  - labels.mss
template: ''
